NAME:NAMYENYA DOREEN
REG NO. : 2022/DCSE/029/SS
    MATHS TEST

In [2]:
import numpy as np
import matplotlib.pyplot as plt

SECTION 1
#Multiple Choice Exercises: Calculate and Select your best solution (Each Question is one Mark)
# 1
A

#2
D

#3
D

#4
A

#5
C

#6
D

#7
A

#8
A, I agree that they are independent, because those that do not live on campus got more As,80 than those that do not live on campus(40)As

#9
D

#10a
B

#10b
a




SECTION2

QUESTION 6



In [5]:
#say numpy array A
A=np.array(([1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]))
A

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [6]:
#transpose of A
A.transpose()

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [15]:

# An Inversion of the matrix Transpose
import numpy as np

#Taking a 3 * 3 matrix
A = np.array([[1, 0.2, 0.5],
              [0.2, 1, 0.8],
              [0.5, 0.8, 1]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))


[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [24]:

import numpy as np
  
# using a 3X3 Numpy matrix A
A = np.array([[1, 0.2, 0.5],
              [0.2, 1, 0.8],
              [0.5, 0.8, 1]])
  
# calculating the determinant of matrix
det = np.linalg.det(A)
  
print("\nDeterminant of given 3X3 square matrix:")
print(int(det))


Determinant of given 3X3 square matrix:
0


Question 5
Given an n-darray X = np.array([[25, 2], [5, 26], [3, 7]])
Generate its shape
What is the transpose of the array
Generate a new n-darray of X scaled up by integer 3 (Hint: note that scalars are applied on each element of a matrix)
Generate a new matrix A = ([[3, 4], [5, 6], [7, 8]]). Compute the matrix multiplication of matrices X and A (note the condition for matrix multiplication must satisfy a certain rule)
Compute the inverse of the result of multiplication of matrices (A and X)


In [43]:

            
X=np.array([[25,2],[5,26],[3,7]]) 
X
#shape of X
(3,2)



array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [27]:
#5 part 4, generating a new matrix
A=np.array([[3,4],[5,6],[7,8]])
A


array([[3, 4],
       [5, 6],
       [7, 8]])

In [34]:
#Matrix multiplication of matrices X and A, only possible if we transpose A
b=A.transpose()
b
#multiplication of matrices X and b(transpose of A)

c=X.dot(b)
c


array([[ 83, 137, 191],
       [119, 181, 243],
       [ 37,  57,  77]])

In [37]:
#inverse of the result of multiplication
import numpy as np
#taking a 3*3 matrix

C=np.array([[83,137,191],
           [119,181,243],
           [37,57,77]])

#Calculating the inverse of a 3*3 matrix
print(np.linalg.inv(C))

LinAlgError: Singular matrix

Question 4: 
Given an n-dim array with enteries: 25, 2, 5;
Generate a numpy array x from the given entries
What is the shape of the array x
What is its transpose
Compute its  𝐿2  Norm


In [38]:
#generating a numpy array x
X=np.array([25,2,5])
X

array([25,  2,  5])

In [44]:
# Shape of the array X
(1,3)

(1, 3)

In [46]:
#transpose of array X
m=X.transpose()
m

array([[25,  5,  3],
       [ 2, 26,  7]])

In [ ]:
# Computing its L2 Norm


Question 2
Assuming heads = 1 and tails = 0, 
what’s the expected value of the toss of a fair coin?
...and of two tosses of a fair coin?
You are one of a thousand people to purchase a lottery ticket. The ticket costs $10 and pays out $5000. What value should you expect from this transaction?

In [ ]:
#Expected value of the toss of a fair coin
fair coin has a probablity of 0.5
Expected value=np
=1*0.5
=0.5



In [ ]:
#for 2 tosses of a fair coin
Expected value=2*0.5
=1

7. Compute the Mean, variance, median, mode of a uniform random variable


In [ ]:
# Mean of a uniform random  variable
f(x)=1/(b-a),if a<=x<=b
E(x)=integral(x/b-a)dx,0 to 1
E(x)=(b+a)/2
E(x)=(1+0)/2=(1/2)=0.5

# variance of a uniform random  variable
E(x^2)=integral(x^2/b-a)dx,0 to 1
E(x)=(b-a)^2/12
E(x)=(1-0)^2/12=(1/12)=0.083

# median

#mode
